In [2]:
import pandas as pd

# csv file in machine

In [13]:
df = pd.read_csv("placement.csv") # with url
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [4]:
df = pd.read_csv("placement.csv") # with name
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

# csv file with url (without machine)

In [5]:
import requests
from io import StringIO

url = "https://gist.github.com/dsternlicht/74020ebfdd91a686d71e785a79b318d4.js"
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko/20100101 Firefox/56.0'}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

                                                                                                                                                      document.write('<link rel="stylesheet" href="https://github.githubassets.com/assets/gist-embed-b34f7d2eef9a0544.css">')
document.write('<div id=\"gist100671240\" class... created by dsternlicht on 11:58AM on January 19 2020.\"\n    >\n\n        <div class=\"blob-int...   open the file in an editor that reveals hidde...

# sep parameter

In [6]:
pd.read_csv("movie_titles_metadata.tsv") # without sep parameter

    m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0    m1\t1492: conquest of paradise\t1992\t6.20\t10...
1    m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2    m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3    m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4    m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                 ...
611  m612\twatchmen\t2009\t7.80\t135229\t['action' ...
612  m613\txxx\t2002\t5.60\t53505\t['action' 'adven...
613  m614\tx-men\t2000\t7.40\t122149\t['action' 'sc...
614  m615\tyoung frankenstein\t1974\t8.00\t57618\t[...
615  m616\tzulu dawn\t1979\t6.40\t1911\t['action' '...

[616 rows x 1 columns]

In [7]:
pd.read_csv("movie_titles_metadata.tsv",sep='\t')  # sep='\t' tells if i have a tsv so data convert into tab separted

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# index_col parameter

agar hme index direct apne data ke dene ho to default ko htana ho

In [8]:
pd.read_csv("movie_titles_metadata.tsv",sep='\t', index_col='m0')   # index_col = 'coloumn name'

,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
m0,,,,,
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...
m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# Header

agar col name row ki tarah treat ho rhe ho to use header

In [9]:
pd.read_csv("movie_titles_metadata.tsv",sep='\t', header=1)    # 1 se start

,m1,1492: conquest of paradise,1992,6.20,10421,['adventure' 'biography' 'drama' 'history']
0,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
1,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
2,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
3,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
4,m6,8mm,1999,6.3,48212.0,['crime' 'mystery' 'thriller']
...,...,...,...,...,...,...
610,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
611,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
612,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
613,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
614,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# Loading a huge dataset in chunks

In [10]:
pd.read_csv("movie_titles_metadata.tsv",sep='\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [11]:
a = pd.read_csv("movie_titles_metadata.tsv",sep='\t', chunksize=100)
a

In [12]:
for chunks in a:
  print(chunks.shape)       # to divide our data into chunks

(100, 6)
(100, 6)
(100, 6)
(100, 6)
(100, 6)
(100, 6)
(16, 6)

# More about CSV files

In [1]:
print('read more')
url = 'https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html'
print(url)

read more
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html